.TH LSC 1
.SH NAME
lsc \- list clients
.SH SYNOPSIS
.B lsc
.RB [ \-als ]
.SH DESCRIPTION
.B lsc
list clients managed by an EWMH-compliant window manager.
Output is one entry per line.
.PP
The options are as follows:
.TP
.B \-a
List the active window whenever it changes.
This option makes
.B lsc
run indefinitely, watching for changes in the _NET_ACTIVE_WINDOW property.
.TP
.B \-l
List in long format (see below).
.TP
.B \-s
Sort by stacking order.
That is, use
.I _NET_CLIENT_LIST_STACKING
instead of
.I _NET_CLIENT_LIST
to get the list of clients.
.SS The Long Format
If the
.B \-l
option is given, the following information is displayed for each client:
client type and state, client window group ID, client transient for window ID,
its window ID, and its window name.
.PP
The first space-separated field consists of a sequence of ten characters,
each one meaning a type state of the client.
If a character is
.B -
the client is normal or the state does not apply to the client.
.IP \(bu 2
The first character indicates the type of the window.
It can be
.B -
(the window is normal),
.B k
(the window is a dock),
.B b
(the window is a bar/dock/panel),
.B t
(the window is a toolbar),
.B m
(the window is a menu),
.B u
(the window is a small persistent utility window, such as a palette or toolbox),
.B s
(the window is a splash screen), or
.B d
(the window is a dialog window).
.IP \(bu 2
The second character is
.B t
to indicate that the window is a transient window (WM_TRANSIENT_FOR);
.B m
to indicate that the window is a modal window (_NET_WM_STATE_MODAL); or
.B T
to indicate that the window is both transient and modal.
.IP \(bu 2
The third character is
.B y
to indicate that the client is sticky (_NET_WM_STATE_STICKY).
.IP \(bu 2
The fourth character is
.B v
to indicate that the client is maximized vertically (_NET_WM_STATE_MAXIMIZED_VERT);
.B h
to indicate that the client is maximized horizontally (_NET_WM_STATE_MAXIMIZED_HORZ); or
.B M
to indicate that the client is maximized to both directions.
.IP \(bu 2
The fifth character is
.B s
to indicate that the client is shaded (_NET_WM_STATE_SHADED).
.IP \(bu 2
The sixth character is
.B t
to indicate that the taskbar should skip the client (_NET_WM_STATE_SKIP_TASKBAR);
.B p
to indicate that the pager should skip the client (_NET_WM_STATE_SKIP_PAGER); or
.B S
to indicate that both the taskbar and pager should skip the client.
.IP \(bu 2
The seventh character is
.B h
to indicate that the client is hidden/minimized (_NET_WM_STATE_HIDDEN).
.IP \(bu 2
The eighth character is
.B f
to indicate that the client is fullscreen (_NET_WM_STATE_FULLSCREEN).
.IP \(bu 2
The ninth character is
.B a
to indicate that the client is above others (_NET_WM_STATE_ABOVE);
or
.B b
to indicate that the client is below others (_NET_WM_STATE_BELOW);
.IP \(bu 2
The tenth character is
.B u
to indicate that the client has the urgency hint set;
.B a
to indicate that the client demands attention (_NET_WM_STATE_DEMANDS_ATTENTION); or
.B U
to indicate that the client is both urgent and demands attention.
.IP \(bu 2
The eleventh character is
.B a
to indicate that the client is active (_NET_ACTIVE_WINDOW);
.B f
to indicate that the client is focused (_NET_WM_STATE_FOCUSED); or
.B A
to indicate that the client is both active and focused.
.PP
The second space-separated field is the number of the desktop the window is in.
.PP
The third space-separated field is the ID of the window group that the client belongs to.
If the client belongs to no group, this ID is 0x00000000.
.PP
The fourth space-separated field is the ID of the window which the client is a transient for.
If the client is not a transient window, this ID is 0x00000000.
.PP
The fifth space-separated field is the ID of the client window itself.
.PP
The remaining space-separated fields are the name of the client.
.SH ENVIRONMENT
The followingj environment variables affect the execution of
.B lsc
.TP
.B DISPLAY
The display where the window manager is running on.
.SH EXAMPLES
The following is an example of the output of lsc run with the
.B \-l
flag.
.IP
.EX
---M------A-   0 0x00000000 0x00000000 0x01400016 lsc.1 + (~/proj/lsc) - VIM
------h-----   2 0x01800001 0x00000000 0x01800003 [No Name] - VIM
---M--------   0 0x00000000 0x00000000 0x03e00016 ttyp1: ~/proj/lsc
------------   1 0x01a00001 0x00000000 0x01a00003 Mozilla Firefox
.EE
.PP
This output indicates that we have a normal Firefox client on the second desktop
(the desktop 1),
two fully maximized clients on the first desktop (one of them is both active and focused),
and a hidden/minimized client on the third desktop.
.PP
In this example, two clients belong to a group. But no client is transient for another window.
.SH SEE ALSO
.IR lsd (1),
.IR lsw (1)
